src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .forms import UserLoginForm


from . import views

urlpatterns = [
    path('ticket/', include('ticket.urls', namespace='ticket')),
    path('account/', include('django.contrib.auth.urls')),
    path('', views.home, name='home'),

    path('login/', auth_views.LoginView.as_view(template_name="login.html",
                                                authentication_form=UserLoginForm), name='login'),

    path('admin/', admin.site.urls),
]

src/ticket/urls.py
from django.urls import path

from . import views

app_name = "ticket"
urlpatterns = [
    path('list/', views.TicketListView.as_view(), name='ticket_list'),
    path('detail/<slug:slug>', views.TicketDetailView.as_view(), name='ticket_detail'),
    path('create/', views.TicketCreateView.as_view(), name='ticket_create'),
]

src/accounts/models.py
from django.db import models

# Create your models here.

src/ticket/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify

CATEGORY_CHOICES = (
    ('categorie1', 'categorie1'),
    ('categorie2', 'categorie2'),
    ('categorie3', 'categorie3'),
    ('categorie4', 'categorie4'),
)

DEPARTMENT_CHOICES = (
    ('IT', 'IT'),
    ('Finante', 'Finante'),
    ('Contabilitate', 'Contabilitate'),
    ('Support', 'Support'),
)

STATUS_CHOICES = (
    ('In asteptare', 'In asteptare'),
    ('In lucru', 'In lucru'),
    ('Terminate', 'Terminate'),
)

class Ticket(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=220, null=False, unique=True)
    author = models.CharField(max_length=300)
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES)
    departament = models.CharField(max_length=50, choices=DEPARTMENT_CHOICES)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='In asteptare')
    content = models.TextField(null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def get_absolute_url(self):
        return reverse('ticket:ticket_detail', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

src/core/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
        attrs={'class': 'input-data'}
        )
    )
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'input-data'}
    ))

src/ticket/forms.py
from django import forms
from .models import Ticket
from django.forms import ClearableFileInput

class MyClearableFileInput(ClearableFileInput):
    initial_text = ''
    input_text = ''

class TicketForm(forms.ModelForm):

    slug = forms.ImageField(widget=MyClearableFileInput)

    class Meta:
        model = Ticket
        fields = ['title', 'slug', 'author', 'category', 'departament', 'content']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['title'].widget.attrs.update(
            {'class': 'form-control'})

        self.fields['slug'].widget.attrs.update(
            {'class': 'd-none'})
        self.fields['slug'].label_suffix = ''
        self.fields['slug'].label = ''
        self.fields['slug'].required = False

        self.fields['author'].widget.attrs.update(
            {'class': 'form-control'})

        self.fields['category'].widget.attrs.update(
            {'class': 'form-select'})

        self.fields['departament'].widget.attrs.update(
            {'class': 'form-select'})

        self.fields['content'].widget.attrs.update(
            {'class': 'form-control'})

src/accounts/views.py
from django.shortcuts import render

# Create your views here.

src/core/views.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

from ticket.models import Ticket

def home(request):
    wating = Ticket.objects.filter(status='In asteptare')[:5]
    working_on_it = Ticket.objects.filter(status='In lucru')[:5]
    finished = Ticket.objects.filter(status='Terminate')[:5]

    return render(request, 'index.html', {'wating': wating, 'working_on_it':working_on_it, 'finished':finished})

src/ticket/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, CreateView, DetailView
from .models import Ticket
from .forms import TicketForm


class TicketDetailView(DetailView):
    model = Ticket
    template_name = 'ticket/ticket_detail.html'
    context_object_name = 'ticketdetail'

class TicketListView(ListView):
    model = Ticket
    template_name = 'ticket/ticket_list.html'
    context_object_name = 'ticketlist'

class TicketCreateView(CreateView):
    form_class = TicketForm
    template_name = 'ticket/ticket_create.html'

src/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <title>Tickts!</title>
    {% block css %}
    {% endblock %}
</head>

<body>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->

    {% block content %}
    {% endblock %}
</body>


</html>

src/templates/index.html
{% extends 'base.html' %}

{% block css %}
<style>
    p,
    span {
        margin: 0;
        padding: 0;
    }

    span {
        font-weight: bold;
        display: block;

    }

    .hidden {
     display:none;
    }
</style>
{% endblock %}

{% block content %}
{% include 'navbar.html' %}

<div class="container-sm">
    

    <h2>Working on Tickets</h2>
    <div class="row">
        {% for ticket in working_on_it %}
        <div class="border border-dark rounded my-1">
            <div class="row">
                <div class="col-8"><a href="{% url 'ticket:ticket_detail' ticket.slug %}"
                        style="text-decoration: none; color: black;">
                        <h3>{{ticket.title}}</h3>
                    </a></div>
                <div class="col-4">
                    <p style="float:right;">by <span style="display: inline;">{{ticket.author}}</span></p>
                </div>
            </div>
            <div class="py-3"></div>
            <em>Problema:</em>
            <p class="pb-1">{{ticket.content}}</p>
        </div>
        {% endfor %}
    </div>

    <h2 onclick="toggler1();">Wating Tickets</h2>
    <div id="working" class="row hidden">
        {% for ticket in wating %}
        <div class="border border-dark rounded my-1">
            <div class="row">
                <div class="col-8"><a href="{% url 'ticket:ticket_detail' ticket.slug %}"
                        style="text-decoration: none; color: black;">
                        <h3>{{ticket.title}}</h3>
                    </a></div>
                <div class="col-4">
                    <p style="float:right;">by <span style="display: inline;">{{ticket.author}}</span></p>
                </div>
            </div>
            <div class="py-3"></div>
            <em>Problema:</em>
            <p class="pb-1">{{ticket.content}}</p>
        </div>
        {% endfor %}
    </div>

    <h2 onclick="toggler2();">Finished Tickets</h2>
    <div id="wating" class="row hidden">
        {% for ticket in finished %}
        <div class="border border-dark rounded my-1">
            <div class="row">
                <div class="col-8"><a href="{% url 'ticket:ticket_detail' ticket.slug %}"
                        style="text-decoration: none; color: black;">
                        <h3>{{ticket.title}}</h3>
                    </a></div>
                <div class="col-4">
                    <p style="float:right;">by <span style="display: inline;">{{ticket.author}}</span></p>
                </div>
            </div>
            <div class="py-3"></div>
            <em>Problema:</em>
            <p class="pb-1">{{ticket.content}}</p>
        </div>
        {% endfor %}
    </div>
</div>

<script>
    function toggler1() {
        var element = document.getElementById("working");
        element.classList.toggle("hidden");  
        }
    function toggler2() {
        var element = document.getElementById("wating");
        element.classList.toggle("hidden");  
        }
    console.log('te salut');
</script>
{% endblock %}

src/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <style>
        .login-wrap{
  width:320px;
  margin: 0 auto;
  margin-top:100px;
  border:1px solid #eee;
  padding:15px;
  background: #f8f8f8;
  border-radius: 4px;
}

.form-group.last { margin-bottom:0px; }
    </style>
    <title>Hello, world!</title>
  </head>
  <body>
    <div class="container">
  <div class="row">
    <h1 class="text-center">Login Screen Using Bootstrap</h1>


    <form class="login-wrap" action="{% url 'login' %}" method="post">
      <form class="form-horizontal" role="form">
          {% csrf_token %}
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-3 control-label">
            UserName</label>
          <div class="col-sm-9">
            {{ form.username }}
          </div>
        </div>
        <div class="form-group">
          <label for="inputPassword3" class="col-sm-3 control-label">
            Password</label>
          <div class="col-sm-9">
            {{ form.password}}
          </div>
        </div>
        <div class="form-group last mt-2">
          <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-primary btn-sm">
              Sign in</button>
          </div>
        </div>
      </form>


    </form>
  </div>
</div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

src/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <a class="navbar-brand" href="{% url 'ticket:ticket_list' %}">Tickets</a>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a style="display: flex;" class="nav-link active" aria-current="page" href="{% url 'ticket:ticket_create' %}"><i class="material-icons">add</i> Ticket</a>
                </li>
                
            </ul>

            
        </div>

        {% if not user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'ticket:ticket_list' %}">Login</a>
        {% else %}
        <a class="navbar-brand" href="#">{{request.user}}</a>
        <a class="navbar-brand" href="{% url 'logout' %}
        ">Logout</a>
        {% endif %}

    </div>
</nav>

src/ticket/templates/ticket/ticket_create.html
{% extends 'base.html' %}

{% block css %}
{% endblock %}

{% block content %}
    {% include 'navbar.html'%}
    <div class="container-sm">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    
{% endblock %}

src/ticket/templates/ticket/ticket_detail.html
{% extends 'base.html' %}

{% block css %}
<style>
    p,
    span {
        margin: 0;
        padding: 0;
    }

    span {
        font-weight: bold;
        display: block;

    }
</style>
{% endblock %}

{% block content %}
{% include 'navbar.html' %}

<div class="container-sm">
    <h2>Tickets</h2>
    <div class="row">
        <div class="border border-dark rounded my-1">
            <div class="row">
                <div class="col-8">
                    <h3>{{ticketdetail.title}}</h3>
                </div>
                <div class="col-4">
                    <p style="float:right;">by <span style="display: inline;">{{ticketdetail.author}}</span></p>
                </div>
            </div>
            <span>Categorie: {{ticketdetail.category}}</span>
            <span>Departament: {{ticketdetail.departament}}</span>
            <div class="py-3"></div>
            <em>Problema:</em>
            <p class="pb-1">{{ticketdetail.content}}</p>
        </div>

    </div>
</div>
{% endblock %}

src/ticket/templates/ticket/ticket_list.html
{% extends 'base.html' %}

{% block css %}
<style>
    p, span {
        margin: 0;
        padding: 0;
    }

    span {
        font-weight: bold;
        display: block;

    }
</style>
{% endblock %}

{% block content %}
    {% include 'navbar.html' %}
    
    <div class="container-sm">
        <h1>Tickets</h1>
        <div class="row">
            {% for ticket in ticketlist %}
            <div class="border border-dark rounded my-1">
                <div class="row">
                    <div class="col-8"><a href="{% url 'ticket:ticket_detail' ticket.slug %}" style="text-decoration: none; color: black;"><h3>{{ticket.title}}</h3></a></div>
                    <div class="col-4"><p style="float:right;">by <span style="display: inline;">{{ticket.author}}</span></p></div>
                </div>
                <span>Categorie: {{ticket.category}}</span>
                <span>Departament: {{ticket.departament}}</span>
                <div class="py-3"></div>
                <em>Problema:</em>
                <p class="pb-1">{{ticket.content}}</p>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}